version: '3'

services:

  db:
    build: ../storage/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounting_db
    ports:
      - "3306:3306"
  adminer:
        image: adminer
        ports:
            - 8080:8080